### ISSUE TITLE
Environment --> Extreme Minimum Temperature Risk tool suggestions

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#1]
*add a legend
*mix match: map shows days with <32 degrees as unit while the chart (below) uses scale of degrees F
![chart](https://cloud.githubusercontent.com/assets/886682/6511113/760f4fbc-c338-11e4-9219-2a3c238fc674.png)

**Comment by daviswx** [comment]
Fixed the timeseries y-axis units.  These are hard-coded for now but will eventually change to be tool-specific.  Also worth noting that the timeseries uses fake data at the moment.  Once the future data is processed and ready, it will be used instead.

**Comment by daviswx** [comment]
The mismatch bug is fixed with commit ncsco/pinemap-dss@b4120dc00e3cd5fa6c93f4faa31dcbca29a5a60e, which includes lots of updates to the timeseries for the Extreme Min Temp Risk tool.

Eventually, tooltips and/or a legend will be added to the timeseries as well.
