### ISSUE TITLE
Minor Bug with Dynamic Hardiness Zones

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#100]
When you initially select your location by clicking the map and then select "Show all time periods", the "Future Emissions" options do not show up:
![image](https://cloud.githubusercontent.com/assets/886682/15677555/c81d7f8c-2718-11e6-9274-c74eb2613aa8.png)

If you click a future 20-year period (with the 5 degree zones shown) radio button and then switch back to "Show all time periods", the "Future Emissions" options show up.

**Comment by daviswx** [comment]
Good catch!  I'll work on it.

Also, **ISSUE #100**!

![image](https://m.popkey.co/7aa178/kv4ol.gif)

**Comment by hadinon** [comment]
I noticed that too... haha, all sorts of milestones here lately!! :stuck_out_tongue_winking_eye:

**Comment by daviswx** [comment]
This should now be fixed on the development site, but could you please double-check to confirm?

**Comment by hadinon** [comment]
Yep, looks good. Thanks!
