### ISSUE TITLE
Layer Options box question

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#101]
One small question about the Layer Options box in the DSS:

On Climate Voyager, I have grouped the "boundary layers" (ecoregions, HUCs, and county lines) together and set them as radio buttons so only one can be selected at a time.  Beneath that, the Ramps locations, Lakes and rivers, and Roads and cities layers are set as checkboxes so they can each be toggled on or off separately.

![image](https://cloud.githubusercontent.com/assets/9257580/17033524/820b8f28-4f4c-11e6-994e-80c675c140ab.png)

For the PINEMAP DSS, should we have the boundary layers use a similar behavior?  This would effectively mean that you couldn't show both county lines and HUCs at the same time.  We could potentially lump the native loblolly range layer in there too, but I can see the benefit of being able to display it in addition to the county or HUC layers.

**Comment by hadinon** [comment]
Yes, let's have a similar behavior on the PINEMAP DSS! As we just discussed, let's plan to have the HUCs and county lines as radio buttons and the native loblolly range layer as a check box.

**Comment by daviswx** [comment]
This is now implemented on the DSS development site.

As a slight side note, the _Lakes and rivers_ layer is now working again.  There was one line in one of their defined styles on GeoServer that caused it to break.  I'm really not sure why since John said he hadn't done any changes to GeoServer lately, but anyway, it's fixed now.

**Comment by hadinon** [comment]
Thanks for the update! Everything looks good so I'm closing this issue.
