### ISSUE TITLE
Map Display Options: Scrolling

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#102]
During the Carolinas Climate Resilience Conference tool demo session, an idea came up about "migrating" the map display options such that those options are always present as a user scrolls down the page. An example of keeping a header static is [this](https://davidwalsh.name/demo/top-bar-opacity.php) except I imagine the map display options part of the page would remain static not the menu options part of the DSS and the opacity wouldn't change. Here's another [example](http://jsfiddle.net/Ja3rp/779/). 

I'm not sure of the feasibility but wanted to mention it. The first example above seems similar to the "time series has loaded" message that you've added to the DSS. Thoughts?

**Comment by daviswx** [comment]
For tools on the PINEMAP dev site, the tool options will now be anchored at the top of the page as you scroll down.  I have tested a few different tools in Chrome and Firefox and it seems to work smoothly in both.
