### ISSUE TITLE
Climate risk tools: minor change to titles

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#11]
This is super minor but wondering if we should change the titles on the center maps to say "average" on some of the climate risk tools to be consistent with that of summer precip, e.g. projected (change) in average number of days ...." and "projected (change) in average summer average temperature". However, the former is quite wordy and the latter sounds repetitive. Thoughts?

**Comment by daviswx** [comment]
I just added "average" to the Extreme Min Temp Risk titles.  It was already there for the Summer Precip. and Summer Avg. Temp tools.  For the latter, should the legend wording say "average summer temperature" instead of "summer average temperature"?  In my mind, this would have the same meaning as "average summer average temperature".

**Comment by hadinon** [comment]
Thanks! And yeah, that one is tricky because it is averaged over the summer months but also averaged across the future time period, e.g. 2020-2039 and 20 climate models. Maybe we can cover all that in a tooltip so I think my vote would be for, "average summer temperature".

**Comment by daviswx** [comment]
Okay, I've changed all mentions in the legend, time series, and the tool name to say "average summer temperature".  Also, I've added "average" to the other climate risk tool legend titles and Y-axis titles where they were missing.

One question: For the tool name, is there any reason to call it the "_Average_ Summer Temperature" tool?  Or would "Summer Temperature" be appropriate, keeping in line with the "Summer Precipitation" title?  Alternatively, should that tool be re-named to "Average Summer Precipitation"?

**Comment by hadinon** [comment]
Thanks! I think we can remove "average" from both of the tools names, too, so that it is "Summer Precipitation" and "Summer Temperature". What do you think?

Also, this is super picky... on the Summer Temperature tool, the time series title says, "temperatures" while the map title says, "temperature". It doesn't matter to me which one we use but I'd say make both the same.

**Comment by daviswx** [comment]
Done and done... the tool name is now "Summer Temperature" and the time series title is now singular "temperature".

On the subject of tool names, should "Extreme Minimum Temperature Risk" be shortened?  Maybe just "Extreme Minimum Temperature"?  Or is "Risk" good to include too?

**Comment by hadinon** [comment]
Thanks! To be consistent with the other climate-based tools, I think we're OK with dropping the "risk". :)

**Comment by daviswx** [comment]
That's done too, so I'll close out this issue.  If any other wording fixes are needed, feel free to re-open this or create a new issue.
