### ISSUE TITLE
Inconsistent time series tooltip text

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#12]
When hovering over time series data, the tooltip text differs between the columns and error bars.

**Comment by daviswx** [comment]
This is now corrected.  The time series tooltips should be the same regardless of whether you hover over the columns or the error bars.

Also, I slightly changed the wording of the tooltips to include "Moderate/Intense warming" instead of the RCP, and to wrap that text to a second line.

**Comment by hadinon** [comment]
Also looks good to me!
