### ISSUE TITLE
Fix Summer Temperature tool color ramps

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#13]
- Revise the **Projected change** color ramp to go up to +15°F
- Revise the **Projected occurrence** time series to start at 60°F

**Comment by daviswx** [comment]
Both of these are now updated.

The Projected change color ramp goes up to +15°F, although based on the RCP 8.5 end-of-century max change map, we could possibly afford to add another degree or two.  Any thoughts on this?

And the Projected occurrence time series begins at 60°F.  Looks much better to me.

**Comment by hadinon** [comment]
Hmmm yeah I see what you mean about the projected change under RCP8.5 and 2080-2099. Maybe try to bump it up to +18F as the max so that most of the PINEMAP region avoids the white color?

**Comment by daviswx** [comment]
This is now updated; the Projected change color ramp goes up to +18°F.  I will close this issue, but please re-open it if you have other suggestions.

**Comment by hadinon** [comment]
Thanks, Corey. Looks good to me!
