### ISSUE TITLE
Gray out unpopulated menu items

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#14]
For menu topics e.g., **Environment** → **Other Weather Conditions**, **Soils**, and **Water**, gray them out and disable clicking to show no tools are available now, but it's on our list.

**Comment by daviswx** [comment]
This is now implemented on the dev site.  Do we need to have a mouse-over or on-click description that tells why these topics are grayed out?

**Comment by hadinon** [comment]
Looks good! Hmmm I'm trying to think how other websites have handled this but I can't think of any good examples. From the options you mentioned, the mouse-over option would be my vote!

**Comment by daviswx** [comment]
The mouse-over text has been added for the grayed-out topics.  If that looks good to you, feel free to close this issue.  Otherwise, let me know if you have suggestions.

**Comment by hadinon** [comment]
Thanks. Looks good to me!
