### ISSUE TITLE
Link to landing pages on each tool

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#15]
Since we got rid of the tooltips containing short descriptions next to each tool's title, we need to link to the landing page at the top of each tool.

**Comment by daviswx** [comment]
I have added a "more information about this tool" link below the tool name.  It links back to the landing page, if one exists (if not, this link doesn't show up).

Closing this issue, but please re-open it if you have suggestions.

**Comment by hadinon** [comment]
Looks great to me!
