### ISSUE TITLE
Time series appearing beneath the bottom banner

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#16]
Apparently caused by vertical screen resolution initially not requiring a scroll bar, then needing to add one when the time series appears.

**Comment by daviswx** [comment]
I _think_ this is fixed on the dev site.  @hadinon, if you could test this out at some point and let me know, that would be great.

**Comment by hadinon** [comment]
Yep, I replicated the issue on the pinemap_dss site and the overlap occurred. Then, using the same zoom level on the dev site, the overlap did not occur. So, I'm marking this as closed. :+1: Thanks!
