### ISSUE TITLE
Seed Development tool Color Confusion

### ISSUE THREAD

**Issue by theotherrmark** [ncsco/pinemap-dss-help#2]
Corey/H: we talked about the confusion created when Historical Map is on in the background. Twenty year projections share the same color patterns as the COLDER TEMPS.......Confusing to say the least.

May need to consider making them textural or at least complementary of existing isotherms because the current patterns draw the eye to the Colder ( below ten degree historical color chart at the bottom) reversing the notion that warming is taking place. THese might be presets but once they are fixed keep them uniform across product..coders and users like that> : )  Thanks
m

As with other issue. Legend denoting LOB histoirc range need to be specified

**Comment by daviswx** [comment]
I've been working on some changes to the Seed Deployment Tool that should have fixed these issues (historical legend colors and ability to toggle map boundaries), and finished several other tasks related to this tool.  Namely, the Seedling Deployment Tools are now two tools:
- a **Seed Movement Tool** that shows where you could move seed from one location for planting in the future
- a **Seed Selection Tool** that shows where you could pull seed from in the future for planting at your location

Before beta testing begins, I still have several other tasks to complete related to this tool, and moreso to the overall DSS layout.  All tools for a given category (like "Seedling Deployment") will be listed in a new submenu, along with a description.  Tool options and legends will be re-arranged to (hopefully) make tool navigation a bit easier.  And I'm planning to add some tooltips to define unfamilar terms (like "RCP scenario") and help with general page navigation.

As we've been developing these tools, @hadinon and I have been compiling a list of questions we may want to ask the beta testers about this tool, such as the way things are worded and displayed.  If you (Mark M. and John H.) think of any such questions we may want to ask, please let us know!

Also, **_one final (but important) note_**.  There is a new URL for the beta tester version of the DSS: [http://climate.ncsu.edu/pinemap_dss](http://climate.ncsu.edu/pinemap_dss)

Please use this URL from now on, as the site we gave you previously will be increasingly used for hammering away at changes, so the pages may be broken or acting funny from time to time.
