### ISSUE TITLE
Summer Temp Tool: Color Ramp Suggestion

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#26]
Maybe remove the green color in the Projected Change color ramp since green could be associated with good? (MEDIUM PRIORITY)

**Comment by daviswx** [comment]
A new Projected Change color ramp is in place for the Summer Temperature tool.  This one removes the green color and goes from yellow → orange → red → purple → pink.

**Comment by daviswx** [comment]
One more suggestion for the Summer Temperature tool:
- Make the time series for the Projected Change display end at +20&deg;F (instead of +30&deg;F)

**Comment by daviswx** [comment]
Also, if possible, add some more variation to the Historical/Projected Average color ramp.  Some maps (e.g., end-of-century multi-model mean) appear as a solid color, which could be confusing.

**Comment by hadinon** [comment]
Quick clarification: I believe the above comment was applicable to the Summer Temperature tool's Projected Change color ramp, not the Historical/Projected Average one (see below for center map in solid red):

![image](https://cloud.githubusercontent.com/assets/886682/15709335/2647b730-27d2-11e6-88dd-5427725c2e1d.png)

**Comment by daviswx** [comment]
I have updated the logic for setting the y-axis bounds on the time series.  Previously, I was using a fixed additive of +5 units on top of the highest value, which was causing some Summer Temperature plots to go up to +30&deg;F even when the highest values were less than +20&deg;F.

Now, I am adding 5% of the difference between the max and min values.  This seems to limit the Summer Temperature time series to +20&deg;F while still leaving room for the labels.

The Summer Precipitation tool should also be improved, although strangely, I can't seem to scale it to every 5 inches.  It always wants to show at least -10 inches to +10 inches.  I don't think that's a problem for this tool, so I probably won't keep investigating it unless this crops up again.

I will work on getting an updated color ramp in place with more variation for the Summer Temperature tool's Projected Change display.

**Comment by daviswx** [comment]
The Summer Temperature tool's Projected Change color ramp has been updated.  The differences are subtle and the middle map at the end of the century still appears mostly red, but there is at least a bit more gradient in the colors.

![image](https://cloud.githubusercontent.com/assets/9257580/15716616/0600bf20-27f1-11e6-8418-681542102738.png)

At the moment, I'm investigating one other sorta-bug with this tool.  The labels on the map and time series appear as `80&deg;F` instead of `80°F`, so I need to get them to recognize the degree symbol.  Unfortunately, I can't just copy and paste that degree symbol into my code because it causes some other funky formatting things on the page.

**Comment by daviswx** [comment]
After a cursory investigation, I'm not sure that there is an easy solution to getting the degree symbol to show up in the map and time series labels without causing a cascading set of unwanted effects elsewhere, so for now I have just removed the degree symbol and I'm showing the labels as "80 F".

That takes care of the Summer Temperature tool suggestions, so if everything looks alright to you, feel free to close this issue.

**Comment by hadinon** [comment]
All looks/sounds good to me! Just one quick question which may or may not be related to this. The time series is currently not working for the Minimum Temperature Thresholds tool. Is that because you are working on that code right now or is it somehow related to the changes mentioned in this thread?

**Comment by daviswx** [comment]
I have been renaming and reorganizing some files on the back end, so that's why it was broken.  It should be working again now.

**Comment by hadinon** [comment]
Yes, it is working so I'm closing this issue. Go Team!
