### ISSUE TITLE
Timeseries legend

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#30]
*Distinguish the legend so it’s clear that those columns aren’t part of the data/plot
*Add a tooltip about the projected ranges: “These confidence intervals represent the range of model projections, not the model error.” and include descriptions for current and reduced emissions (can probably copy the verbiage within the existing Future Emissions tooltip)
(MEDIUM PRIORITY)

**Comment by hadinon** [comment]
Additional idea from Corey (discussed at today's PINEMAP meeting)... have a total of 3 different tooltips related to RCP's, highlighting different information within each:

**For the menu**

Future Emissions tooltip: "These scenarios account for potential greenhouse gas (GHG) emissions due to changes in energy production, global and local economic circumstances, and population growth.  Both scenarios are Representative Concentration Pathways (RCPs) defined by the Intergovernmental Panel on Climate Change (IPCC)."

**For the map legend**

RCP 8.5/Current Levels tooltip: "Under current or high emission levels, greenhouse gas emissions steadily increase through the year 2100.  This corresponds to the IPCC's RCP 8.5."
RCP 4.5/Reduced Levels tooltip: "Under reduced or moderate emission levels, the total radiative forcing, or change in energy in the atmosphere due to GHG emissions, stabilizes shortly after 2100.  This corresponds to the IPCC's RCP 4.5."

**For the timeseries legend:**

RCP 8.5/Current Levels tooltip: "This confidence interval represents the range of model projections -- not the model error -- across 20 climate model simulations with current (or high) emission levels."
RCP 4.5/Reduced Levels tooltip: "This confidence interval represents the range of model projections -- not the model error -- across 20 climate model simulations with reduced (or moderate) emission levels."

So this basically presents similar information in three different locations.  It also keeps the blurbs fairly short.

**Comment by daviswx** [comment]
The new tooltip wording is now in place in the menu, the map legend, and the timeseries legend.

To take care of the other part of this issue, I added a light gray border around the timeseries legend.  Hopefully this makes it clear that it's not part of the timeseries data.
