### ISSUE TITLE
Map Legend

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#32]
*Boldface the legend title
*“Time Period: 2020 to 2039 (as compared with 1950 to 2005)”
*Add better tooltips/info for map navigation (people didn’t understand they needed to click the map title to enlarge, and there was a tendency to double-click to zoom; this works but it also selects a new location)
(HIGH PRIORITY)

**Comment by daviswx** [comment]
Updates:
- The map title is now in bold.  My only lingering question is about the capitalization (see ncsco/pinemap-dss-help#36).
- I added the note about the baseline period and took a first crack at writing a tooltip for it.
- For the map navigation tooltip, I wonder if we might want to have one central tooltip somewhere around the map that explains how to interact with it.  Maybe above one of the small maps, we could have a link that says something like "Map Tutorial" or "How to use these maps".  Hovering over it would reveal a tooltip that explains things like how to enlarge the small maps, clicking on the large map to select a location, and interacting with the maps (panning, zooming, turning on new layers).  This would mean we could also get rid of the "Click any of the small maps' titles to enlarge them" tooltip and have room for the projected occurrence explanation, as discussed in ncsco/pinemap-dss-help#31.

**Comment by hadinon** [comment]
In thinking more about this, can you add the word "model" before the word baseline in the baseline period tooltip? 

Sort of related, I wonder if somewhere we should link to this MACA analysis page. There are some really good tips on here! http://maca.northwestknowledge.net/MACAanalysis.php

I look forward to seeing the map navigation tooltip that we discussed yesterday. :+1:

**Comment by daviswx** [comment]
- The baseline period tooltip has been updated.
- That is a useful link about MACA analysis.  Maybe we could add that to the Other Resources section at the bottom of the page?  To be honest, I think it's probably more informative than the generic MACA link we have now.
- The new **Map Help** tooltip is now in place.  Let me know if you have any suggested wording tweaks.

**Comment by hadinon** [comment]
Everything looks great with the **Map Help** tooltip. :+1: 

And yes, I agree about adding that link to the other resources section! Once that's done, I think this issue is closed. Thanks!

**Comment by daviswx** [comment]
Just added that link for the climate risk tools.
