### ISSUE TITLE
Tooltip Suggestions

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#33]
*Shorten the Future Emissions tooltip
*In the historical time period tooltip, rewrite to eliminate “it spans enough time to account for a range of climate variations” and say “to capture variation (droughts, cold snaps, etc.)”
*Drop the navigation tooltip style and convert to one standard design
(MEDIUM PRIORITY)

**Comment by daviswx** [comment]
Along with these suggestions, I am planning to slightly re-do the way tooltips are created.

Going to just one tooltip style is part of it.  The other part is creating a single tooltip repository script.  That way, the tooltip text doesn't need to be copied to every single place that uses it.  This will also make it much easier to update tooltips.

**Comment by daviswx** [comment]
The new tooltip plan is in place.  This will make it much easier to update tooltips, keep them consistent from one page to the next, and add them to the DSS.

I shortened the Future Emissions tooltip but there is probably still room to shorten it more.

Also, I revised the historical time period tooltip as Aim6 suggested.

Because we have gone to just one tooltip style, I removed the Tooltips tab from the main DSS landing page.  However, if the purpose of these tooltips isn't clear, we can re-add this tab back or just mention it on a different tab.

**Comment by hadinon** [comment]
I agree with all your changes, including the length of the Future Emissions tooltip :+1:

**Comment by hadinon** [comment]
<b>For the menu</b>

Future Emissions tooltip: "These scenarios account for potential greenhouse gas (GHG) emissions due to changes in energy production, global and local economic circumstances, and population growth.  Both scenarios are Representative Concentration Pathways (RCPs) defined by the Intergovernmental Panel on Climate Change (IPCC)."

**For the map legend**

RCP 8.5/Current Levels tooltip: "Under current or high emission levels, greenhouse gas emissions steadily increase through the year 2100.  This corresponds to the IPCC's RCP 8.5."
RCP 4.5/Reduced Levels tooltip: "Under reduced or moderate emission levels, the total radiative forcing, or change in energy in the atmosphere due to GHG emissions, stabilizes shortly after 2100.  This corresponds to the IPCC's RCP 4.5."

For the timeseries legend:

RCP 8.5/Current Levels tooltip: "This confidence interval represents the range of model projections -- not the model error -- across 20 climate model simulations with current (or high) emission levels."
RCP 4.5/Reduced Levels tooltip: "This confidence interval represents the range of model projections -- not the model error -- across 20 climate model simulations with reduced (or moderate) emission levels."

So this basically presents similar information in three different locations.  It also keeps the blurbs fairly short.
