### ISSUE TITLE
Menu option bug

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#34]
*When switching from Projected Change to Historical or Projected Occurrence, the Projected Change name disappears
(HIGH PRIORITY)

**Comment by daviswx** [comment]
This should be fixed now that the menus have gone from vertically stacked to horizontal.

As best as I can tell, this was a really funny side effect of showing and hiding the Future Time Slice and Future Emission menu options.  The "Projected change" text itself didn't actually go away; it showed up again if you highlighted that part of the menu with your cursor.  But for some reason, it just seemed to disappear when you clicked off of the Projected Change layer and selected one of the other Map Display options.
