### ISSUE TITLE
General page capitalization

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#36]
*capitalize most words in the menu options, legend titles, map titles, time series titles
(LOW PRIORITY)

**Comment by daviswx** [comment]
This has been updated so the menus and titles capitalize all major words.  I think it looks fine in most places, but in my opinion, it really doesn't look good in the legend title and time series title.  I think it makes them tough to read, and many scientific figures don't adhere to this rule.

Let me know if you have any strong feelings one way or the other.  Maybe this could also be a question to ask the beta testers.

**Comment by hadinon** [comment]
Hmmm yeah, let's pose this question to beta testers! Google Forms has an option to insert images so maybe we can have a radio button question with the two options for text capitalization within the titles. Thoughts?

**Comment by daviswx** [comment]
Yes I like this idea, let's ask the beta testers.  Not sure if we'd need to show images or if we could just give text examples with the radio buttons (e.g., **Projected Average Number of Days Per Year with Minimum Temperatures < 32°F** vs. **Projected average number of days per year with minimum temperatures < 32°F**) and ask for their preference.

**Comment by hadinon** [comment]
Sounds good. I've got this down on my list of beta tester questions!

**Comment by daviswx** [comment]
An overwhelming majority (8 to 2) of beta testers prefer the current capitalization of almost every word.  So I will leave it as is and close this issue.
