### ISSUE TITLE
Clicked location box

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#37]
*Populate the latitude and longitude text boxes with the clicked location
*Change the lat and lon box text color to gray
*Make the clicked location unselectable?  Add an X in this box to clear the selection?
*Move location box below the legend and above the map; if this results in lots of white space, might need to change map display options to be horizontal instead of vertical
(HIGH PRIORITY)

**Comment by daviswx** [comment]
I have started experimenting with moving the Location box away from the menu and closer to the map.  Here are a couple examples showing it in different locations:

**A. Above the map**
![map_location_box-a](https://cloud.githubusercontent.com/assets/9257580/9735830/8c05a8f0-560b-11e5-8491-6ea28498e4f0.PNG)

**B. Below the map**
![map_location_box-b](https://cloud.githubusercontent.com/assets/9257580/9735837/940c62dc-560b-11e5-917d-9c4fea5c1b49.PNG)

I can think of pros and cons to each.  With **A**, it puts all the map details together, but it gets in between the legend and the maps themselves.  With **B**, it keeps the maps higher on the page, but it may not be as easy to see, and it takes up the same space as the 5° range legends on the seedling deployment tools.

Note: I removed the Map Layers legend in both of these examples.  I will probably replace those options (city and road layers, loblolly range layer, county lines toggling) with either icons on the map or a layer switcher panel on the map.

**Comment by daviswx** [comment]
The menu options have also been changed to be listed horizontally.

This is a nice way to save vertical real estate and reduce white space, but it means the menu categories (like Map Display) aren't quite as "modular" or visually connected any more.

Here's an example I thought of for creating some visual separation between menu items without adding much or any clutter:

![menu_box_separated](https://cloud.githubusercontent.com/assets/9257580/9737031/9bd897a4-5612-11e5-86a8-75423f0a8d56.PNG)

**Comment by hadinon** [comment]
Personally, I like option <b>B</b> better but I was remembering that the seedling deployment beta testers mentioned not knowing that there was information below the map. So, I'm leaning towards option <b>A</b>. Can you try to center the text above the middle map? Also, just curious, what would the behavior be if you decide to maximize one of the side maps? e.g. would the location information be populated above that map or would it stay centered above all 3 maps? I'm fine with either way.

In terms of your visual separation example, I love it!

**Comment by daviswx** [comment]
I feel the same way about the positioning.  It looks better below the map but it's probably easier to see and more functional above the map.

Yes, I will make sure it is centered on the page.  The plan will be to have it stay in that position (like the legend) no matter which map is enlarged.

**Comment by daviswx** [comment]
Here's one other idea I just thought of for the location box display:

![map_location_box-a2](https://cloud.githubusercontent.com/assets/9257580/9741155/d3fa59c4-5626-11e5-88b1-908a083a109c.png)

Do you like this overall layout any better than having the legend colors and location box stacked?  Obviously we could move individual elements around, like centering the Time Period and Future Emissions scenario beneath the title rather than above the color scale.

**Comment by hadinon** [comment]
As we discussed at our meeting, I really love option <b>A</b> with location information centered above the map. After you implemented these changes, I noticed a few bugs with the seedling deployment tools (see #42).

**Comment by daviswx** [comment]
I just added an '[X]' box in the legend to clear the selected location from the map and hide the timeseries.

That takes care of the suggestions for the marker location box, so I will close this issue.  If other suggestions or bugs come up, please re-open it.

**Comment by hadinon** [comment]
If you select a valid location from the map (any tool, I believe) and then click again on an invalid location, the '[X]' box in the legend does not disappear: 

![image](https://cloud.githubusercontent.com/assets/886682/9768180/056cd7b0-56f0-11e5-9782-990f7236516a.png)

In fact, you can click the '[X]' to clear the selected location from the map but the message, "Complete time series data is unavailable for your selected location" still appears:

![image](https://cloud.githubusercontent.com/assets/886682/9768205/306eaf24-56f0-11e5-8502-6f063aba0e03.png)

**Comment by daviswx** [comment]
This should now be fixed.  After you click to select a new location, the [X] box should automatically go away.
