### ISSUE TITLE
Page header

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#38]
*Try changing header text and link colors to gold, yellow, or some higher contrast color.  Also increase the link font size. Mimic changes made to pinemap.org site
(LOW PRIORITY)

**Comment by daviswx** [comment]
I just changed the "Decision Support System" text and link color to be a lighter green, and I increased and bolded the link font.  This should provide some additional contrast to make this text more visible.

If changes are made to the main pinemap.org site, we can come back and edit the DSS header to match.
