### ISSUE TITLE
Seedling Deployment Tools: Map Display Bugs

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#42]
After the changes were made to the layout of the Map Display options (horizontal layout instead of vertical, see issue #37 ) , I noticed a few bugs with the seedling deployment tools...

1) After initially selecting your location by clicking on the historical map, I tried toggling back to the historical map by clicking the radio button under Map Display. However, the historical map is not returned. This is the result:

![image](https://cloud.githubusercontent.com/assets/886682/9746679/616468e8-5647-11e5-809f-c8559bad4d0b.png)

2) Starting from where I left off in step 1, if I then hit "Show 5 degree range" for 2020-2039 and finally click the "Projected Temperatures" radio button under Map Display, something really weird happens with the isotherms (it looks like the 5 degree range is being overlaid with all of the other projection layers):

![image](https://cloud.githubusercontent.com/assets/886682/9746741/a3cf9e82-5647-11e5-995a-a0271ec53e21.png)

Are you able to replicate?

**Comment by daviswx** [comment]
Yes, I was able to replicate it, and it should be fixed now.  It was caused by a JavaScript error related to a change I made earlier today.

**Comment by hadinon** [comment]
While double checking to make sure #9 was fixed, I found two issues (shown below) with the Dynamic Hardiness Zone tools although I'm not entirely sure these issues are related to #9. Here's my process for obtaining these bugs:

_**Bug 1**_: Select a location somewhere in the ocean (I could see someone accidentally doing this). The message pops up indicating that projected data is unavailable for your selected location but the selected radio button becomes the "Location-Specific Ranges" one yet the data being displayed is the Historical Average map. 
![image](https://cloud.githubusercontent.com/assets/886682/16620850/00abf7c4-4362-11e6-8e5e-fbd438d05e43.png)

_**Bug 2**_: Select a location somewhere over land and when the "Location-Specific Ranges" display shows up, click "Show all time periods". Then, click somewhere in the ocean (again, I could see someone accidentally doing this). Again, the message pops up about projected data being unavailable at that location but the isotherm layers remain "turned on". I thought we decided to keep it turned off in these cases but I could be remembering incorrectly.

![image](https://cloud.githubusercontent.com/assets/886682/16620923/4f0f96aa-4362-11e6-9eff-4d7195567be5.png)

**Comment by daviswx** [comment]
This issue got lost in the chaos a few weeks ago, but I just revisited it and I think it's fixed now.  If a selected location is not valid, the Historical Temperatures display will show up.

I will close this issue in the next commit to the public DSS site.

**Comment by hadinon** [comment]
Yep, looks fixed to me so I'm closing it.
