### ISSUE TITLE
Very minor bug with seedling deployment tools

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#45]
After initially selecting my  location by clicking on the historical map, I then selected one of the "show 5 degree range" options. Everything works fine so far! If I toggle back to the historical map by clicking the radio button under Map Display and then toggle back again to the projected temperatures, everything is displayed as I would expect with the exception of the "hide 5 degree range" text, which is still appearing (see below option for "Seedling source for a 40-year stand"). Is there a way to change that back to "show 5 degree range"?

![image](https://cloud.githubusercontent.com/assets/886682/9852783/17442ccc-5ace-11e5-82d9-46df592709ed.png)

**Comment by daviswx** [comment]
Fixed now.  I just had to call the function that resets those menu options.

**Comment by hadinon** [comment]
Similarly, can you call that same reset function in this instance described below?

Select a location and show one of the 5 degree ranges. Then, switch to the other emission scenario.

**Comment by daviswx** [comment]
Done.

**Comment by hadinon** [comment]
Thanks :+1:  I didn't even re-open it because I figured it'd be a quick fix!
