### ISSUE TITLE
Location information: Bug with [x]

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#46]
Ok, here are my steps....

1) On the Summer Temperature tool's Historical Occurrence tab, I select a location.
2) Then I decide that I don't want that particular location and thus, I use the [X] option in the location information section. So far so good.
3) Next, I switch to the Projected Change tab and it remembers my most recently clicked location and populates that in the location information section. It also puts values on the map (with no marker) for that location as well as pulls up the time series for that location). Expected behavior would be to populate "none selected" in the location information section. Can you replicate?

![image](https://cloud.githubusercontent.com/assets/886682/9853359/349f66c6-5ad1-11e5-9a4c-66943394a6f4.png)

**Comment by hadinon** [comment]
Note: this only seems to apply to the climate tools but I found a similar issue with the seedling deployment tools. Here's my steps....

1) Select a location from the map. 
2) Then I decide that I don't want that particular location and thus, I use the [X] option in the location information section. So far so good.
3) Hit one of the "show 5 degree range" options and it shows the values and 5 degree range for the most recently clicked location (see below). That got me thinking... on this tool, don't we almost always need a location defined in order to show any of the projected temperature information? If yes, maybe we: a) don't have an [X] option on this tool or b) when a user clicks the [X], have it go back to the historical temperature graph essentially refreshing the tool so they start over again by selecting a new location from the historical map. Thoughts?

![image](https://cloud.githubusercontent.com/assets/886682/9853825/a9fdbbc8-5ad3-11e5-9cfe-edf94ffdc35d.png)

**Comment by daviswx** [comment]
The problem on the climate tools with the location re-appearing should be fixed.  I just had to un-set the location variables once the [X] is clicked.

I will work in implementing our agreed fix to the seedling deployment tools: When the [X] is clicked on the Projected Temperatures map, the isotherms will disappear and a message will appear in the map legend saying something like "Select a location to view projected temperatures".

**Comment by daviswx** [comment]
The new behavior for the seedling deployment tools is now in place.  When the selected location is removed, the isotherms will disappear and a message will in the legend saying "Select a location to view projected temperatures".

If you then switch back to the Historical Temperatures display, the Projected Temperatures menu option will be grayed out and disabled until the map is clicked and a new location is chosen.

**Comment by hadinon** [comment]
OK, just noticed a behavior on the seedling deployment tools that is related to this issue. Here are my steps: 
1) Select a location from the map. Then I decide that I don't want that particular location and thus, I use the [X] option in the location information section. So far so good.
2) I switch the Future Emissions option and the "data unavailable" message pops up as well as the location information stating that projected data is unavailable for your selected location. Is there a way to fix that such that it only displays, "select a location to view projected temperatures" and "location: none selected"?
![image](https://cloud.githubusercontent.com/assets/886682/9961701/f345d710-5def-11e5-9434-182f5a3561ec.png)
3) Related, if you then click the historical temperatures map display option, it says that projected data is unavailable for your selected location; however, the projected temperatures radio button is grayed out as expected. Is there a way to make the location information say "none selected"? I'm guessing that fixing step 2 will also fix this but wanted to mention it.
![image](https://cloud.githubusercontent.com/assets/886682/9961760/4cd6f12e-5df0-11e5-8e89-86e90fc9e829.png)

**Comment by daviswx** [comment]
The issue in step 2 should now be fixed.  If no location is selected, the page won't do anything when the Future Emissions dropdown is changed.

As you suspected, this seems to have also fixed the problem in step 3.

Could you try this on your end and close this issue if it's fixed for you too?

**Comment by hadinon** [comment]
Yep, looks to be fixed so I'll go ahead and close it. :+1:
