### ISSUE TITLE
Add the matrix/list of tools

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#48]
Before beta testing, this list should be ready so the "View All Tools" link on the main landing page is functional.

Any ideas about the best way to structure this?  And what info. should be included about each tool?

**Comment by hadinon** [comment]
Here's how the AgroClimate folks do their matrix of all tools: 
![image](https://cloud.githubusercontent.com/assets/886682/9997644/540d2e50-605b-11e5-8fbc-15e017c1932d.png)

I like their design but one concern of mine is using an image for each tool. As we've experienced with the SCO website, sometimes it can be challenging to assign an image with each tool.

Another option is to distinguish (bold, underline?) the tool name and then give a brief 1-2 sentence description of the tool. Maybe state what it is and why it's important to forestry?

Thoughts?

**Comment by daviswx** [comment]
Agreed about the images.  It would be tough to find unique images for all of our tools unless we went abstract and used photos like trees with icicles on them or something.  I'm fine with leaving off the images unless Aim6 wanted to commit to finding them for us.

To populate this matrix, I was planning/hoping to pull from the information we already have about each tool, which includes its short description in the menu.  Of course, that's more like one sentence in most cases, and based on Steven Weaver's suggestion, we _removed_ the forestry applications from these.  We could always write matrix-specific descriptions for each tool, but that's just one more piece of information we have to add and update.

If we used the tool names and short descriptions, it would basically look like the AgroClimate matrix without the images.  So then we'd have to decide if there's any other information we want to display, like maybe the menu and topic in which it's grouped (e.g., "Environment → Temperature" for the Summer Temperature tool).

Also, do we want to display all the tools at once or break them up into tabs based on the four menus?  Looks like the AgroClimate page has an option to view everything or filter based on specific applications.  Since we have relatively few tools available now, the filter option may not be as important, but it's probably good to decide whether it's needed to make our lives easier down the road.

One more question that I can think of right now: Should the "View All Tools" button link to a separate page or show the tools in the space on the landing page where we're showing text and images?  I can see benefits and drawbacks to both approaches.

**Comment by hadinon** [comment]
Yep, I agree about the images so let's plan to leave them off.

I also agree about using the same short descriptions as in the menu. 

I think it'd be neat to tie the menu and topic groupings (while also having an option to truly "show all"), whether that be explicitly listing it out for each tool or breaking them into tabs. Or, a combination of both? Do you have a preference?

In terms of what happens when you click "View All Tools", I could be convinced either way but I'm leaning towards having it pop out to a new page because this will give us more space and be consistent with the "Proceed to the Tool" button on the tool-specific pages. Thoughts?

**Comment by daviswx** [comment]
In the matrix, I was thinking we could list the menu and topic for each tool, either above the tool name or below the description.  Here's a mockup:
![viewalltools_matrixa](https://cloud.githubusercontent.com/assets/9257580/10000196/a7a1a214-6068-11e5-9103-abc0ca3dd37b.PNG)

We could also do this without color-coding the menus and topics (i.e., put them all in gray) since they aren't currently color-coded in the main menu.

I can also see how it would be useful to view only topics and tools within a given menu, so I can add checkboxes for those.  And I think we discussed this a while back, but I may eventually add a search box, so if someone searches for "temperature", it would retrieve any tools with "temperature" in the name or description.

I also prefer having View All Tools link to a separate page for the reasons you mentioned, plus it lets you give someone a direct link if they want to see all the available PINEMAP tools.

**Comment by hadinon** [comment]
Looks great! I'm OK with it either way in terms of the color-coding. Checkboxes and a search box both sound good. :+1:

**Comment by daviswx** [comment]
The first version of the tool matrix is finished.  To access it, go to the main DSS landing page and click "View All Tools".

**Comment by hadinon** [comment]
Nice work! I really LOVE it. :+1:  :+1:  :+1:

**Comment by daviswx** [comment]
One last question about this: As I'm reviewing/editing the beta tester questions, I realize that I'm referring to this page by several different names: the DSS Tools page, the "View All Tools" link, and the tool matrix.

I figure we should stick with one name to cut down on confusion and use that name in the landing page link and for the page title.  Any preference about which name is best?

**Comment by hadinon** [comment]
Hmmm good question! What about DSS Tool Matrix or DSS Tool List? I don't have strong feelings about this so feel free to suggest another name.

**Comment by daviswx** [comment]
I was leaning toward tool matrix myself, so I will go with DSS Tool Matrix.

... and it's done!
