### ISSUE TITLE
Seedling deployment tool legend updates

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#49]
When viewing the 5° ranges, show the rounded temperatures in the attached legends and add the map marker icon below the isotherm temperature.

**Comment by daviswx** [comment]
This is done, but IMO having the marker icon hanging out in the legend begs the question of why it's there.  So we may need to add a tooltip somewhere in the legend explaining what these ranges represent and what temperature they're centered on.

I will brainstorm some ideas, and maybe we can discuss this at our "pow-wow" tomorrow.

**Comment by hadinon** [comment]
Yes, I agree. Let's discuss at our "pow-wow"!

**Comment by daviswx** [comment]
- Make the legend text bold
- Add a small tooltip icon in the upper corner of the marker icon
- Tooltip wording:
  - **Seedling Markets:** This is your location's historical annual average minimum temperature.
  - **Seedling Sources:** This is the min/mean/max projected temperature for your location for the [20x0-20y9] time period given [current/high] emissions.

**Comment by hadinon** [comment]
Super minor detail: I just noticed that we've been calling the historical maps "average annual minimum temperature" on the seedling deployment tools so we may want to adjust the **Seedling Markets** tooltip wording to match that.

**Comment by daviswx** [comment]
These new tooltips are in place.  I'm not sure how good the icon looks positioned in the top right corner of the marker.  I also tried putting it at the bottom right but it didn't necessarily look any better.  Any suggestions?

**Comment by hadinon** [comment]
Hmmm what if you change it to look something like this (see below center map)?
![image](https://cloud.githubusercontent.com/assets/886682/10077939/9021e064-62b0-11e5-9d99-bd7d7acb3c9a.png)
I "inspected the element" in Chrome and changed the tooltip style= to say "left: 2px;".

**Comment by daviswx** [comment]
Sure, I think that looks a bit better.  I changed it and set it to 1px.

One other small thing I just discovered with the seedling deployment tools is that the marker labels don't show a ".0" for temperatures that round evenly to an integer.  I will fix that to be consistent with the other tools.

**Comment by hadinon** [comment]
Another idea: is it possible to put the tooltip to the right of the bolded number? Here's what that looks like but it seems a bit cluttered to me.

![image](https://cloud.githubusercontent.com/assets/886682/10078111/5206a750-62b1-11e5-9c74-2830eba6f2fd.png)

**Comment by daviswx** [comment]
I thought about that as well, but like you said, I think it's just too cluttered and it may not even be clear which number it applies to.

Also, the number rounding issue should be fixed, so all numbers will show one decimal place on the map labels and in the attached legends.

**Comment by hadinon** [comment]
Agreed. In the tooltip, do you think we should mention something about how the 5 degree ranges represent 1° cooler to 5° warmer than that min/mean/max projected temperature?

**Comment by daviswx** [comment]
I would say no for those tooltips since they specifically apply to that one temperature value.  And hopefully that part is self-explanatory in the legend since the temperatures are listed there.

**Comment by hadinon** [comment]
Yeah, that's true. OK I'm going to go ahead and close this issue.
