### ISSUE TITLE
DSS Overview Landing Page: Layout/Usability

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#52]
*Keep current tabbed layout.
*Re-write the final sentence above the tabs to note what users are supposed to do on the page.
*Use numbered tabs. 
*Link to resources about IPCC/climate guidance? (assigned to HAD)
(HIGH PRIORITY)

**Comment by daviswx** [comment]
Introductory wording and tab names/numbers have been updated.  We don't currently link to IPCC anywhere, so this can be added if needed (maybe when discussing the future emissions scenarios? or somewhere else?).

**Comment by hadinon** [comment]
Yes, that sounds good about IPCC info when discussing future emissions scenarios. Here are a few reference options:
- https://www.wmo.int/pages/themes/climate/emission_scenarios.php
- http://sedac.ipcc-data.org/ddc/ar5_scenario_process/RCPs.html
- https://www.ipcc.ch/pdf/supporting-material/expert-meeting-ts-scenarios.pdf

**Comment by daviswx** [comment]
I added the first link on the Climate Data tab and mentioned the RCPs in the descriptions.  Please re-open this issue if you have any suggestions.
