### ISSUE TITLE
DSS Overview Landing Page: Graphics

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#53]
*Contact Aim6 about creating new graphics that don't look as much like screenshots. (LOW PRIORITY)

**Comment by hadinon** [comment]
Emailed Leslie to see if SREF graphic designers are still willing to help with this. She is going to talk with Bill and Laura (graphic designer) and get back to us with a timeline.

**Comment by hadinon** [comment]
Meeting with Laura and Leslie on Tuesday 11/17 to discuss a plan of action.

**Comment by hadinon** [comment]
Action item here: Laura to send us new images with "computer screen" design once new menus and/or other landing page changes have been implemented.

**Comment by hadinon** [comment]
Update: Laura sent a Photoshop file with computer screen so that we can insert any screenshot.

Also, Leslie made these suggestions which will be implemented soon:
- switch the DSS Introduction layout from tabs to left side navigation
- within the DSS Introduction, change the "DSS Tools" title to "About DSS Tools"
- fill the entire space on the DSS Introduction page

**Comment by daviswx** [comment]
Using the file Laura sent, I created a new image for the "About DSS Tools" tab on the dev site.  Take a look and let me know what you think.

I can also draft up similar images for the other tabs, keeping the annotations for the Climate Data and Three-Map Layout tabs.

**Comment by hadinon** [comment]
I like it! This is a **rough** sketch but what about a layout like this for the Climate Data tab?
![example_climatedatatab](https://cloud.githubusercontent.com/assets/886682/12725401/846bafac-c8e0-11e5-8c01-0864b78adc16.png)

**Comment by daviswx** [comment]
Here's my attempt at that design.  What do you think?  And would you suggest any changes to the layout or wording?  I'm thinking the text could probably be a bit smaller so it's not squished against the edges of the image.

![climate_data_new_v1](https://cloud.githubusercontent.com/assets/9257580/12726573/5e2198ce-c8e6-11e5-8afc-14e2efd37817.png)

**Comment by daviswx** [comment]
And here's what I have for the Three-Map Layout tab:

![three_map_layout_new_v1](https://cloud.githubusercontent.com/assets/9257580/12727784/6f91c83a-c8ec-11e5-9e01-3cf312bea544.png)

**Comment by hadinon** [comment]
Nice work! Here are a few comments/suggestions/questions on the Climate Data one:
- I agree about reducing font size a bit
- 2nd bullet under Historical: can we change this to, "Assessment of recent conditions from 1986 to 2005" (since all the historical maps are averaged across that time period)? Or, we could drop "recent". Thoughts?
- For consistency with the bullet about MACA, should we say, "From University of Idaho METDATA dataset"? I realize that sounds a bit odd/repetitive so I'm fine if you want to leave it "as is" (without the word "dataset")

I have no suggested edits for the Three-Map Layout image. Looks good! :+1:

**Comment by daviswx** [comment]
New images have been added to the landing page, including an updated Climate Data image and a Time Series image.

**Comment by hadinon** [comment]
Thanks for the update. OK, I'm clearing my cache but the Climate Data image still says 1950 to 2005 instead of 1986 to 2005 :wink:

**Comment by daviswx** [comment]
For some reason, images are really slow to update in Chrome sometimes, even when you're clearing the cache.  It's updated, I promise, so it might just take a few minutes to display.

**Comment by hadinon** [comment]
Ah yes, I just checked in Firefox and it is updated. That's so weird about Chrome! Anyways, the only remaining action items on this thread are:
- switch the DSS Introduction layout from tabs to left side navigation
- fill the entire space on the DSS Introduction page

However, as we discussed, those two items are not required before we push changes to the public version of the DSS.

**Comment by daviswx** [comment]
Suggestion from Ryan: Add a zoomed inset at the bottom of the Time Series image to show one time slice + the tooltip + the legend.

**Comment by daviswx** [comment]
The Time Series image has been updated to include a zoomed inset at the bottom.  This change is now reflected on the public site.  (You may need to clear your cache to see it, though. :wink:)

**Comment by hadinon** [comment]
Haha. Or don't use Chrome apparently! I was able to see it in Firefox. Looks great. :+1:

**Comment by daviswx** [comment]
I have updated the Introduction page on the dev site to have the tabs listed down the left side instead of across the top.  This ended up filling up the horizontal space as well.

I also got rid of the buttons to go to the previous tab and the next tab.  With the list as it is, I thought they were unnecessary, and there's not a great place to put them anyway,

**Comment by hadinon** [comment]
All sounds good and I think this issue is resolved. Please reopen if there are other changes that need to be implemented.

**Comment by daviswx** [comment]
Suggestion from Ryan: On the Time Series image, change the inset to a lighter gray or another color.

**Comment by hadinon** [comment]
Another suggestion from Ryan: Within the Time Series text, describe the historical variability bar.

**Comment by daviswx** [comment]
I have updated the Time Series image and added an explanation of the Historical Observed bar.

**Comment by hadinon** [comment]
This is so nitpicky that I'm not even going to reopen the issue... can you remove the period at the end of the sentence about the historical observed bar? None of the other bullets within the DSS Intro tabs have a period associated with the statement

**Comment by daviswx** [comment]
Done. Period. :wink:
