### ISSUE TITLE
DSS Overview Landing Page: More Background Info

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#54]
*Add an initial tab noting basics about pine trees and the PINEMAP project, and why tools use climate information.  Use an image of pine trees so the initial image doesn’t look like the menus. (MEDIUM PRIORITY)

**Comment by hadinon** [comment]
Title ideas for this tab would be "Background" or "Basics". Proposed text for this new tab is:
-  Pine Integrated Network: Education, Mitigation, and Adaptation project (PINEMAP) studies planted pine forests in the Southeast US
- Pine trees influence their local climate yet are also themselves sensitive to climate factors including temperature and precipitation
- Therefore, many of the DSS tools utilize climate data to explore these relationships 

In terms of images, what do you think of one of these? http://www.pinemap.org/photos/loblolly%20cone2.jpg/image_view_fullscreen
http://www.pinemap.org/photos/loblolly%20form.jpg/image_view_fullscreen

I was thinking we might include one of the pine tree images above and another image to represent temperature or precipitation. Thoughts?

**Comment by daviswx** [comment]
I think this will work.  Once I update the landing page, I will add this in.

**Comment by hadinon** [comment]
This appears to be done and looks good to me. Please re-open if you see any other issues.
