### ISSUE TITLE
DSS Overview Landing Page: Text

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#55]
*On each tab, reduce text using bullet points and bold when applicable 
*Add this to the Three-Map Layout tab: “click the map to select your location” 
*Add this to Climate Data tab: "time period (til 2099)"
(HIGH PRIORITY)

**Comment by hadinon** [comment]
Here's my attempt to reduce text to bullet points:

**Structure tab**
- Tools broken into 4 categories related to major stand considerations: environment, stand establishment, management, and both market and non-market production
- Subcategories under each of the four categories, e.g. Environment includes Temperature, Precipitation, and Drought
- Clicking a subcategory, e.g. Temperature, reveals tools related to that topic
- Note: DSS works best with current version of any major browser in full-screen mode

**Climate Data tab**
- Climate dataset used: University of Idaho's Multivariate Adaptive Constructed Analogs (MACA) 
- MACA aims to simulate physics / chemistry of our atmosphere / oceans to paint a picture of climate at a local scale over several decades or longer 
- Two different scenarios and spread of future outcomes shown, not just a single average future climate state 

[[note: I would link the word MACA to their website: http://maca.northwestknowledge.net/ and maybe add "2 future emission scenarios" as a bullet on the image? Add another bullet point that says, "time period (out to 2099)". Also, statistically speaking it would be more appropriate to replace all DSS instances of (on this page and in tooltips, legends, etc.) the word "range" with "spread" (see example in third bullet above).]]

**Three-Map Layout tab**
- Center map: mean of all 20 global climate models
- Left map: 2.5th percentile of all 20 global climate models
- Right map: 97.5th percentile of all 20 global climate models
- Map Features: click map to select your location, double-click to zoom, click and drag to pan, click side map titles to enlarge that map

**Time Series tab**
- summarizes the historical average and future projections for your location
- each future bar shows the mean and spread of all 20 global climate models
- note: the model error is not shown yet

**Comment by daviswx** [comment]
I have updated the wording on the overview page and bolded some important words/phrases.

The Time Series tab seems a bit short on information, so maybe we can add a bit more detail.  Let's re-visit this once we get the faded bars design in place.

**Comment by daviswx** [comment]
I have updated the time series image on the DSS Introduction landing page to show the faded bars.  Of course, once we get help from the SREF graphic designer, this will be replaced.

Can you think of any additional text to add for the Time Series tab?

**Comment by hadinon** [comment]
Looks good. As far as additional text for the time series tab, what about adding a bullet saying that the time period and RCP represented by the map(s) above will be highlighted in bold and dark green with a marker indicating the RCP. Thoughts?

**Comment by daviswx** [comment]
Good idea.  I added a bullet about that and another about hovering over the bars to see more information.  I will close this issue for now, but we can always come back later if we have other ideas for the wording.

**Comment by hadinon** [comment]
Yep, that sounds good. Closing this issue!

**Comment by daviswx** [comment]
Per suggestions from Ryan and Katherine Hegewisch, tweak the wording on the **Climate Data** tab:
- Say "Global climate models aim to..." instead of "MACA aims to"
- Add a sub-bullet to that section saying "MACA connects GCMs/global scales to local scales at a sufficient resolution for decision making"
- Add another bullet about the UI Met Data

**Comment by daviswx** [comment]
Updated wording is in place on this tab.  Please review this and offer suggestions if you have any.

**Comment by hadinon** [comment]
Slight tweaks suggested below:
- Future projections come from a set of global climate models, which aim to simulate the physics and chemistry of our atmosphere, land, and oceans to paint a picture of climate over several decades or longer.
- DSS tools are based on the University of Idaho's Multivariate Adaptive Constructed Analogs (MACA) dataset, which connects larger scale output from global climate models to local scales at a sufficient resolution for decision making.

If you agree, I will send Katherine the new text to make sure she's OK with our edits.

**Comment by daviswx** [comment]
I have added this tweaked wording.  One thing I don't like is that this tab is very wordy now, and it actually requires vertical scrolling to see everything.  This gets away from our goal of short bullet points to emphasize the main ideas.  I wonder if the current information might be better on the MACA FAQ page, which we could link at the bottom of the text?  And if we could reduce the tab contents to just the basic information about the climate data.

**Comment by hadinon** [comment]
Yeah, I agree. I'm thinking the material would be reduced to: 
- Historical data in the DSS comes from the University of Idaho's METDATA
- Future data in the DSS comes from the University of Idaho's Multivariate Adaptive Constructed Analogs (MACA) dataset, which connects large-scale output from global climate models to local scales at a sufficient resolution for decision making
- Two different emissions scenarios and a spread of future outcomes are shown instead of showing only a single future climate state
- Emissions scenarios: Current levels (high, or RCP 8.5) and reduced levels (moderate, or RCP 4.5)
  - Future time period: present to 2099

We can probably even remove "which connects large-scale output from global climate models to local scales at a sufficient resolution for decision making" if we wanted to shorten it more. Thoughts? 

I'll get to work on that MACA FAQ for DSS. :smile:

**Comment by daviswx** [comment]
OK that shortened wording is now in place.  I do like at least mentioning global climate models on this page since otherwise it doesn't really give any indication of what MACA is or where the data comes from.  I still think it's worthwhile to have a more detailed explanation on the FAQ page, too.

**Comment by daviswx** [comment]
Suggestion from Ryan: Add a graph on the Climate Data tab to explain the RCPs.  Here's one from USGS that we could possibly use:

![image](https://cloud.githubusercontent.com/assets/9257580/13503011/52668fea-e13b-11e5-9322-3eeffd29eed9.png)

http://pubs.usgs.gov/fs/2015/3042/images/fs2015-3042_fig02.png

**Comment by hadinon** [comment]
Looks great to me!

**Comment by daviswx** [comment]
I have added this image to the Climate Data tab.  I also moved the "Future time period" bullet point to beneath the "Future projections..." section so it wasn't all alone beneath the image.

**Comment by hadinon** [comment]
Looks good! One thing that I thought of the other day... we may need to adjust the text on the Three-Map Layout tab now that the Historical Observed also has three maps. Maybe we could have two headings: "Historical Data" and "Future Projections" with two bullets under each: 1) center map and 2) side maps. Then, put the "Map Features" as a heading below that with four bullets (Single-click to select a location, double-click to zoom, click and drag to pan, click map titles to enlarge) or just one bullet with all four, depending on space. Thoughts?

**Comment by daviswx** [comment]
Yes, I like this idea.  That tab has always been a bit thin on content.  I have updated it with your suggestions, although I didn't put the map features as separate bullets since it would've forced the text in that box to scroll, and I try to avoid that if possible.

Let me know if any wording changes are needed.

**Comment by hadinon** [comment]
Yep, looks great. Super minor tweak: can we change the word "range" to "spread" under "Historical Data - Side maps"? Other than that, I think we can re-close this issue.

**Comment by daviswx** [comment]
Done.
