### ISSUE TITLE
DSS Overview Landing Page: Tool Matrix

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#57]
*Show the Tool Matrix within a tab on the Overview page. (HIGH PRIORITY)

**Comment by hadinon** [comment]
This change has been superseded by issue #59. Please re-open if there's something you'd like to re-visit with it.

**Comment by daviswx** [comment]
Based on suggestions from SREF and changes to the menu structure noted in #77, embed the tool matrix to the DSS Introduction landing page.

Should this be the first thing that DSS visitors see on the page?  Or should they still have to step through the other tabs first?

Also, remove the color-coded menus and possibly add topic-specific icons later.

**Comment by hadinon** [comment]
I personally think I'm going to have to see it before making a decision as to whether the embedded matrix should be the first thing DSS visitors see on the page so if you have a preference, go with that first and we can go from there. Sound good?

**Comment by daviswx** [comment]
Agreed, I'm hoping I might be struck with inspiration for this design at some point.  I'll first get the embedded matrix ready and we can go from there.

**Comment by hadinon** [comment]
After new DSS Intro page changes (e.g. side menus and new images) are pushed to production, touch base with SREF to see if matrix is still needed.

**Comment by hadinon** [comment]
On Feb 18th, I emailed SREF folks and haven't heard any feedback from them. Maybe we should follow the mantra "no new is good news" and close this issue? We can always re-open later if needed.

**Comment by daviswx** [comment]
Sounds good to me.  Since then, we removed the mini tool matrix so it may not make sense to have a full-sized one to complement it anyway.
