### ISSUE TITLE
Tool-Specific Landing Pages

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#58]
*Replace tool-specific landing pages with expandable FAQ boxes on the tools themselves.  Collapse them by default, but show teaser text like “Did You Know: Side maps show data…”. 
*Remove the “more information about this tool” link. 
(HIGH PRIORITY)

**Comment by daviswx** [comment]
The tool-specific landing pages are gone (sayonara! :wave: ).

In their place, I have added several FAQ boxes on each tool:
- A box next to the tool name gives a general tool description.  I took the wording for these from the old landing pages.
- Two boxes above the map.  One contains the old Map Help tooltip text about the map features, and the other, which only appears when viewing the Projected Change or Average display, gives a description of the side maps.
- A box below the time series legend with an overview of the time series plot.

I will leave this issue open for now in case you have any suggestions for the wording.

**Comment by hadinon** [comment]
One comment on the time series FAQ: 

Channeling my inner statistician, can we change the part that says, "...near the extremes (more transparent colors)" to say, "...near two standard deviations above/below the mean (more transparent colors)". I don't love that wording but I do like the fact that it reiterates these values are two standard deviations above/below the mean (not extremes or model error). 

Another option might be: "...near the edges of the bar (more transparent colors), which represent two standard deviations above/below the mean". If we go with this, we could change the "near the mean" part to say, "near the center of the bar (more opaque colors), which represents the mean..."

Thoughts?

**Comment by hadinon** [comment]
A few more comments about both seedling tool FAQ boxes:
- Should the side map FAQ box show up when "projected temperatures" is selected? 
- Can we change the "what can this tool be used for?" FAQ to say, "This tool builds on historical guidelines from..." instead of, "This tool is based on guidelines from..." -- basically, I want to emphasize that we are not replicating Schmidtling's guidance but instead, hopefully enhancing it by incorporating information about future migration of minimum temperature ranges but maybe that is already obvious with the text that mentions future range locations in the first paragraph of this FAQ?

**Comment by daviswx** [comment]
Sorry for the delayed response about this.  I just noticed your comments about this issue.

The wording for the time series FAQ box and seedling deployment tool FAQ boxes has been updated.

Also, yes, the side map FAQ box should show up for the seedling deployment tools.  I forgot to code that in before, but it should be working now.

I will close this issue since I think the FAQ boxes are done, but as always, please re-open it if anything else comes up.

**Comment by hadinon** [comment]
*Add "Click to hide the answer" to the FAQ box when it is open (to make it obvious that's how you collapse it).

**Comment by daviswx** [comment]
Done.  Text at the bottom of the FAQ boxes now says "(click to hide)".
