### ISSUE TITLE
New Menu Layout

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#59]
*Mock up possible new menu layout, with PINEMAP logo and links on the left side.
*Add menu and submenu next to/above tool name, color-coded like on the tool matrix.
(MEDIUM PRIORITY)

**Comment by daviswx** [comment]
Once the mockups are ready, we may want to get some opinions on them.  Should that be restricted to just us, or folks from our office, or a broader team from PINEMAP?

**Comment by daviswx** [comment]
I have mocked up several ideas for possible menu re-designs.

**A. Current layout** _(for comparison purposes)_
![dssintroduction-a](https://cloud.githubusercontent.com/assets/9257580/11068696/86f523c4-87a0-11e5-9dd9-b56269ce7e3f.png)

**B. Shrink PINEMAP logo, move up current menu structure**
![dssintroduction-b](https://cloud.githubusercontent.com/assets/9257580/11068705/99650b64-87a0-11e5-92ce-b621f5859658.png)

**C. Embed the tool matrix at the top of the page** _(we could shrink the text and padding if needed to fit additional tools)_
![dssintroduction-c](https://cloud.githubusercontent.com/assets/9257580/11068711/a7b230ac-87a0-11e5-9cc4-76a134c90f5b.png)

**D. Add a new color-coded condensed menu** _(not sure how the tools would show up; could be linked to the Tool Matrix or pop up a new pane displaying them over the menu and topics)_
![dssintroduction-d](https://cloud.githubusercontent.com/assets/9257580/11068740/ced5083a-87a0-11e5-9722-5c58c2b78d9d.png)

**Comment by hadinon** [comment]
Once the final mockup is ready, do you want to get opinions from the beta tester group? We could send it via email and give them a few days to respond with feedback. Thoughts?

**Comment by daviswx** [comment]
For the sake of expediting the DSS updates, it may be easier to proceed with whatever changes we decide on internally.  It seemed like the beta testers liked that basic idea, so maybe we could email them after some of the other changes are made, but potentially before the rollout.

**Comment by hadinon** [comment]
Yes, agreed. Plus, that's the process we followed last time and it seemed to work out well.

**Comment by daviswx** [comment]
The new tool matrix-style menu is now implemented and functional.  The menu (or category) and topic name are also color-coded and listed next to the tool name.

Closing this issue now but please re-open if other issues come up.
