### ISSUE TITLE
Map Help Tooltip

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#60]
*Possibly remove the Map Help tooltip and put that information in the expandable FAQ box below the map. (MEDIUM PRIORITY)
*Fix the Map Help tooltip so it still shows up when mousing off of question mark. Note: not needed if we remove Map Help tooltip. (LOW PRIORITY)

**Comment by daviswx** [comment]
The Map Help tooltip has been removed, and that information is now in the FAQ box above the map.
