### ISSUE TITLE
Location selection: county dropdown?

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#61]
*Before implementing a county dropdown option for location selection, ask Aim6: "what information are professional foresters likely to have/know about their lands, e.g. county, lat/lon?" because our first round of beta testers said they will always know lat/lon but our second round of beta testers said they will always know county, not necessarily  lat/lon. (LOW PRIORITY)

**Comment by hadinon** [comment]
Sent an email to Aim 6 soliciting guidance on this

**Comment by daviswx** [comment]
Based on the guidance from Aim6, do you think we have a clear idea about this?

**Comment by hadinon** [comment]
Responses to this were pretty evenly split. I see this as being logistically challenging for several reasons. For example, do you select the center of a county? If yes, will users think it represents a county average? So, what if we give them the option of **zooming** to a county, state of interest instead of **selecting** a county, state location. I have concerns about the amount of "stuff" already listed above the map (e.g. title, legend, location selection, etc.) but I have an idea for how this could work without taking up an extra line vertically. I'll come tell you in person and then scan in my hand drawn image after our discussion. :)

**Comment by hadinon** [comment]
Another idea from Corey: have this zoom feature in the bottom right corner of the map (where the Map Help tooltip used to be).

Updated timeline on this: implement sometime after the initial roll-out.

**Comment by hadinon** [comment]
Decided not to implement at this time
