### ISSUE TITLE
Tooltip Suggestions

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#65]
A few comments from the beta tester survey:
*Slightly tweak historical average and future time period tooltip wording (assigned to HAD)
--include why we use 1986-2005 (wanted to represent the most recent 30-year rotation period and/or say that droughts and cool seasons impact stand productivity?)
*Add historical average tooltip to timeseries legend 
*The use of "or" to mean "that is to say" in a couple of different places might be confusing for some users. Maybe use e.g.?
*do we need to add a tooltip on the time series plots stating that they can mouse over the time series to see all the values?
(MEDIUM PRIORITY)

**Comment by hadinon** [comment]
Proposed wording for historical average tooltip: "This historical period represents the current or recent climate in which pine trees are being grown. It signifies the most recent 30-year rotation period and spans enough time to capture variations that impact tree productivity, such as severe droughts and cool seasons."

Proposed wording for future time period tooltip: "Future Change = Climate Projection - Climate Model Baseline Period. The baseline period (1950-2005) is not actual observed climate data; instead, it is a free-form forecast that covers a historical climate period. Future Average = Historical Average + Future Change." starting a newline after each of those and maybe a space between the baseline period sentence and the Future Average equation.

**Comment by daviswx** [comment]
The Time Period tooltip above the map has been updated with the proposed wording above.  I just re-ordered the second one to have both equations below the baseline explanation.

I also changed the word "or" to a backslash "/" when referring to the emissions scenarios in the tooltips.

**Comment by hadinon** [comment]
*change behavior of the "show all tooltips" to be show/hide instead of mouse over

**Comment by daviswx** [comment]
Also change the behavior of individual tooltips so you must click them to show/hide the text.

**Comment by daviswx** [comment]
The updated tooltip functionality is now in place:
- For each tooltip, the :grey_question: icon must be clicked to display the full text.
- Once the full text is displayed, clicking the icon or the text box will hide it.  A "click to hide" note has been added to the bottom of each box.
- Clicking the "show tooltips" control will display the full text for all tooltips on the page, and clicking "hide tooltips" will hide all of the text boxes.

I also made the text boxes slightly narrower with a smaller font size, and I positioned them below each icon instead of above them to keep any tooltips from overlapping with the "show/hide tooltips" control.

I do have one question.  We're using the terms "show" and "hide" for both the master FAQ control and the master tooltip control in the upper right corner of the page.  However, the behavior is slightly different.  Showing/hiding the FAQ boxes adds or removes those elements from the page entirely, while showing/hiding the tooltips keeps the :grey_question: icons on the page but shows/hides the expanded text explanations.

So should we use different wording for one of these?  Like for the tooltip control, say something like "expand/collapse tooltips" or "turn on/off tooltips"?

**Comment by hadinon** [comment]
I just wanted to make a note that we decided to wait until historical variability calculations are finished before adding a historical avg tooltip to timeseries legend as noted in #51. Also, we decided not to add a tooltip to the time series plots stating that users can mouse over the time series to see all the values. Instead, this verbiage was added to the DSS intro page under the "Time Series" tab.

Changes all look great! Yes, I agree about changing the "show/hide" terms for one of those. I like your  "turn on/off tooltips" suggestion but would be OK with either of your ideas.

**Comment by daviswx** [comment]
The tooltip control wording is updated to say "expand tooltips" and "collapse tooltips".  I decide to go with these because, after thinking about it more, it seemed like "turn on" meant the same thing as "show", i.e., displaying the icons rather than the tooltip contents.

**Comment by hadinon** [comment]
Verbiage needs to be changed on the projected average map tooltips (lowest likely outcome, multi-model mean, and highest likely outcome) within the climate risk and opportunities tools. Currently, the tooltips say, "The Minimum/Mean/Maximum Projected average...and the Minimum/Mean/Maximum Projected Change".

**Comment by daviswx** [comment]
This is now updated.  For the middle map, I added the words "outcome" and "change", since it might be confusing to say "The Multi-Model Mean is the sum of the Historical Average and the Multi-Model Mean".

**Comment by hadinon** [comment]
Super minor bug... I just went to Summer Avg Temp tool and turned on the Historical Avg Time Period tooltip. Then I switched to Projected Average. None of the tooltips were on (as expected) but I wanted to turn all of the tooltips on so I went over to hit "Expand tooltips" except it said "Collapse tooltips". So, I guess my question is, what should be the default behavior when switching to different map displays? It would be nice if all tooltips are collapsed (and thus, the expand/collapse tooltips is changed to expand tooltips). Note: when I went back to the Historical Avg map display, the tooltip was still expanded. Thoughts?

**Comment by hadinon** [comment]
Also, the tooltip for "Lowest Likely Outcome" says, "...and the Least Likely Change". Should that be "Lowest Likely Change"?

**Comment by daviswx** [comment]
I'm fine with collapsing all of the tooltips whenever the map display is changed.  I can't necessarily see any reason that the page should remember which ones were open and re-open them when a different display is chosen.

The only possible exception would be the tooltip next to the Future Emissions dropdown in the menu.  If you're switching from Projected Change to Projected Average, an argument could be made that the tooltip should remain open.  But one could also argue that changing the map display should "refresh" the page to provide a uniform look every time it's selected.

**Comment by hadinon** [comment]
Yeah, I would prefer the "refresh" way that you described. What do you think?

**Comment by daviswx** [comment]
The new tooltip behavior (collapse all when changing map displays) is now implemented for the climate risk tools and the seedling deployment tools.

**Comment by hadinon** [comment]
Just noticed this... should the historical average tooltip on climate risk and opportunity tools say, "It signifies the most recent 20-year" instead of "30-year", or is my brain on vacation already?!

**Comment by daviswx** [comment]
Yes, you're correct.  I have fixed the problem in commit ncsco/pinemap-dss@96cd3d6.
