### ISSUE TITLE
Time series background colors not centered on zero

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#66]
See the Summer Precip. tool projected change plot for an example; the white shading is not centered around zero.

Also, could this particular time series span from -10 to +10 instead of -20 to +20.

**Comment by hadinon** [comment]
Agreed about changing the time series y axis. It may need to range from -15 to +15 based on looking at min/max values across the PINEMAP domain.

**Comment by daviswx** [comment]
The colors on the time series should be centered up a bit better now.  I just went in and tweaked the code until I found something that seemed to work.

I have also set the Summer Temperature and Summer Precipitation tool time series to go up in increments of 10 instead of 20.  This means that the Summer Precip. change plots generally span from -10 to +10, although if values are near the edge or just outside of this range, it can go to -20 and/or +20.

The Extreme Minimum Temperature tool still spans in increments of 20.
