### ISSUE TITLE
Add contact information

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#73]
*Add our contact information to the DSS so people can report bugs, ask questions, etc.
--where should this go? bottom of the page?

**Comment by hadinon** [comment]
A few ideas for where this could go...
- top left part of the header section of the DSS -- maybe underneath the line with "v1.0"?
- somewhere in the bottom footer section of the DSS
- on the DSS Introduction page? (least favorite idea because this is not always visible to users, e.g. when you are on tool pages)

Thoughts?

**Comment by daviswx** [comment]
I'd say the footer might be the best place for it, in a paragraph below "The Pine Integrated...".   Should we provide the general SCO email or one of our specific email addresses?

**Comment by hadinon** [comment]
Sounds good to me. I wonder if there's a way to get people to email both of us in the mailto? Maybe with one of us as a "cc:"?

**Comment by daviswx** [comment]
Task: Check to see if we can set up a new email address, like pinemap at climate.ncsu.edu

**Comment by daviswx** [comment]
I have added this wording at the bottom of the page:

If you have any questions, suggestions, or bugs to report with the PINEMAP DSS, please email us at **pinemap&commat;climate.ncsu.edu**.

Once that email address goes live, I will add that to the changes we'll push to the public site.

**Comment by hadinon** [comment]
Yep, looks great! Once that email address goes live, feel free to close this issue.

**Comment by hadinon** [comment]
As of yesterday, the alias has gone live so I'm going to close this. Feel free to re-open if needed.
