### ISSUE TITLE
Time Series Mouse Over Text

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#75]
On Climate Risk tools, the mouse over text on time series needs to be changed to reflect the new map titles, e.g. lowest likely, multi-model mean, and highest likely instead of minimum/mean/maximum projected.

Can you think of any other locations these new titles would need to be updated?

**Comment by daviswx** [comment]
This is now updated.

I just did a grep for "projected change" and it seems like we've caught everything that needs to be updated.
