### ISSUE TITLE
Create an "About the DSS" page

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#78]
Include credits for the creators and a change log with the latest version number.  Link to it in the "About" menu.

**Comment by daviswx** [comment]
This page, called "DSS Development", has been created and is linked through the "About" menu on the dev site.

In the top text, should we include credits for specific tools and datasets?  Like should we credit Gary for helping with the seedling deployment tools, and Evan/VT for providing the model output?  Or should these credits go with the specific tools, or somewhere else?

And is there any other development information that should be included?

**Comment by hadinon** [comment]
I like it! Yes, we should credit individuals that helped with tools. Maybe we could include that information on this DSS Development page and then add a link to it from each tool, possibly listed under the "Resources" at the bottom of each tool page?

**Comment by daviswx** [comment]
I've added a note about Gary's help on the development page, and I have text commented out about Evan helping with the productivity model data.  I guess for now, that's about all we need to do with this page, unless you can think of anything else.

**Comment by hadinon** [comment]
Sounds good. Did we decide to get rid of the "Resources" section at the bottom of each tool? I don't see it there anymore and can't remember if we discussed removing that.

**Comment by daviswx** [comment]
Oops, I commented it out for the eye tracking site and forgot to comment it back in on the dev site.  I'm working on it.

**Comment by daviswx** [comment]
It's fixed now.

**Comment by hadinon** [comment]
Great, thanks. I believe this issue is resolved so I will close it. As always, reopen if needed.
