### ISSUE TITLE
Verbiage on DSS Intro: Climate Data Tab

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#81]
Comment from Tomasz Koralewski:
- Introductory screen, tab “3. Climate Data”, Future time period (last bullet):
  Does “present” mean “2015”, or is it dynamically updated?

**Comment by hadinon** [comment]
We did this because some tools, e.g. seedling deployment tools, have future periods from 2010-2029 while most others have future periods starting in 2020-2039. So, there are a few options for how to handle this:
1) explain this to Tomasz and see if he's OK leaving it "as is"
2) change it from "present" to "2006 to 2099" but that may be confusing to folks since 2006 is not technically a future year since it's 2016
3) say "2010" or "2020" instead of "present"

Thoughts?

**Comment by daviswx** [comment]
Will any of the model outputs include data for years from 2006 to 2020?  If not, I'm fine with changing this to "2020 to 2099".  Otherwise, I'm not sure that we can specify an initial "present" year since it may change from tool to tool.

**Comment by hadinon** [comment]
We are not anticipating any model outputs starting at year 2006 at this time so I'm thinking option 2 is out. The seedling deployment tools should be an anomaly with output starting from 2010-2029 so I'm good with changing it to "2020 to 2099".

**Comment by daviswx** [comment]
I have changed "present" to "2020" on the Climate Data tab.
