### ISSUE TITLE
Add HUC layer options for regional modeling tools

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#86]
Suggestion from Ryan: For regional modeling tools, add HUC12 layer to "Show Layer Options" (as long as it is relatively quick to draw).

**Comment by daviswx** [comment]
We could also set up this option to display a variety of HUC layers, from HUC-2s to HUC-12s, like Rebecca has in the [Water Portal](http://climate.ncsu.edu/water/map/) under Map Options.

**Comment by hadinon** [comment]
Yep, good idea!

**Comment by daviswx** [comment]
The HUC boundaries have been added in the Layer Options panel.  I do want to update the borders so they aren't so thick, but I wasn't able to change the styles in the WMS call, so I may need to consult John about doing that in GeoServer.

I tested this with Chrome and Firefox and the lines are relatively quick to render, so we shouldn't have any concerns about that.  I think it must just be GeoJSON layers that cause problems in Firefox.

Although we initially discussed having these for only the regional modeling tools, I think it's fine to have them available for all tools.

**Comment by hadinon** [comment]
Looks good and I agree about having them as an option for all tools. They are really fast to draw!

One thing that I noticed is the brightness -- which is maybe not the best way to describe it but that's the best word I can come up with right now! -- changes when going from overlaying HUC6 (or larger) to HUC8 (or smaller). For an example, see the maps below from the Extreme Min Temp tool:

HUC6:
![image](https://cloud.githubusercontent.com/assets/886682/13088154/0d574b9e-d4b9-11e5-8e50-5ac85f8962e1.png)

HUC8:
![image](https://cloud.githubusercontent.com/assets/886682/13088132/052a1b7c-d4b9-11e5-8e6c-eb54b84827cf.png)

Are you able to replicate? FWIW I like the brighter one (e.g. HUC6 above) better. Thoughts?

**Comment by daviswx** [comment]
Yes, I think that's because of the default styles used for the HUC 8-12 layers.  Now that the blog post is done, I will work on updating those.

**Comment by daviswx** [comment]
The HUC layer styles should now be updated so they are transparent on the inside and the borders aren't as thick.  I just needed to set the style parameter in one other location to get it to work.

**Comment by hadinon** [comment]
Looks good! Closing this issue but as always, feel free to re-open if needed.
