### ISSUE TITLE
Seedling Deployment Tools: How to Visualize Error

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#88]
I thought I'd open an issue about this to capture some of our ideas discussed during recent PINEMAP meetings. The goal is to figure out how to handle model error for these two tools. Our ideas include:
- have another option called "show error" listed under each time period above the map, similar to the "show 5 degree range" option. This allows us to avoid the issue of having too many layers overlaid on the same map because you would only show the value + error for one 20-year time period at a time.
- on the map itself, how should we colorize and distinguish the error from the mean/mean+2std/mean-2std range? We could make the error hashed although OpenLayers may not support this OR we could make the error the same color but change the opacity a bit.
- another idea (possibly difficult to execute) would be to check if the model error exceeds the shift and if so, don't show it

Feel free to add any other ideas to this thread.

**Comment by daviswx** [comment]
I tried to summarize our overall thoughts on visualizing model error in issue #91, and I included and referenced these ideas about the seedling deployment tools in that thread.  Also, I noted the option to show the error for each time slice in the mock-ups in issue #80.

Just so our thoughts aren't spread across three different issues, I will close this one unless there's a compelling reason to keep our discussion of displaying error for the seedling deployment tools in a separate issue.
