### ISSUE TITLE
Highlight the need to choose a location

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#92]
Based on the preliminary eye tracking results, it seems that some users still have a tough time knowing that they can click on a location.  We have discussed several ways to remedy this:
- Put the text "**Location:** none selected" in a larger font.  We could also add an explanation after this like "(click the map to select a location)", but that would be redundant with the text on the line below.
- After the page loads, have this Location box slowly pulse a different background color until a location is chosen.
- If the user hasn't selected a location after a certain amount of time (1 minute?), have a "Clippy"-style dialog box creep in telling the user that he can view more details by clicking a location.
- Before the time series is displayed, add some placeholder text noting what will appear there when a location is selected.

**Comment by daviswx** [comment]
We discussed adding one other page feature that's semi-related to this.  Ryan suggested highlighting each map in a sort of animation after a projected display is selected.

Although I'm not a fan of actually enlarging and shrinking all three maps in succession -- as a user, I think that would be quite off-putting -- I could try having each map _title_ change its background color in succession.

I'd consider this a lower-priority addition, but I wanted to document it anyway.  If I explore more JQuery animations for the other tasks in this issue, I may look into this one as well.

**Comment by daviswx** [comment]
I have implemented a couple of these suggestions about the location box:
- I put the text in a larger font, but for now I didn't add any additional text (like "click the map") since it would repeat the instructions on the line below.  I did put that instruction text in italics, which could make it more visible.
- The location box will pulse light red until a location is selected.

**Comment by hadinon** [comment]
Nice! What about this idea? I added "click the map or enter coordinates below" to the "Location" part  which has larger font and also removed the line of text on the second line and just had the lat/lon text boxes there instead. Obviously, the part that says "click the map or enter coordinates below" would go away once someone selects their location but I think that's OK because they will know HOW to change their location at that point. Note: I envision that the location box will still pulse light red until a location is selected. Thoughts? 

![image](https://cloud.githubusercontent.com/assets/886682/13813328/4f14c3e0-eb57-11e5-9e4d-53d45f8a27ae.png)

**Comment by daviswx** [comment]
I have mixed feelings.  The instructions to click the map may be more noticeable if they're in a larger font like this, but I worry that removing them completely once a location is chosen may cause confusion.  What if a user accidentally clicks the map and selects a location, then doesn't know how to change it?  It sounds ridiculous, but it could happen when double-clicking to zoom.

I'm hoping that the current approach with having the location box (including the instructions) flash red will make that step a lot more obvious to users.  At least to me, the italicized instructions also stand out a bit more than standard text.  Note that I could make the font one size larger if it would help the instructions stand out even more:

![image](https://cloud.githubusercontent.com/assets/9257580/13814403/812945a4-eb5c-11e5-8b39-81823dc6d183.png)

**Comment by daviswx** [comment]
I have added in some placeholder text below the map:

_To view a summary chart of all time periods, select a location on the maps above._

It goes away once a location is selected.

**Comment by daviswx** [comment]
Other than forcing Clippy on people, the suggested changes have been made, so I am closing this issue.

**Comment by daviswx** [comment]
Ryan suggested making the location box background color pulse slightly faster so it's a bit more obvious.  I will update it.

**Comment by daviswx** [comment]
I have sped up the pulsing by 25%.  I think it's more noticeable now without being too distracting.

**Comment by hadinon** [comment]
Yep, looks good to me! Closing this but feel free to re-open if needed.
