### ISSUE TITLE
Shade the native loblolly range layer

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#94]
*current loblolly range layer is KML but I will send @daviswx a polygon shapefile so he can fill them in

**Comment by daviswx** [comment]
Sounds good.  I will upload this to GeoServer once I have it in hand, and I can create a custom style with a semi-transparent fill color.

**Comment by hadinon** [comment]
Sounds like a plan. You should have the file(s) in your inbox. :+1:

**Comment by daviswx** [comment]
The new loblolly range shapefile has been added to GeoServer and to the DSS.  I tried to set the fill opacity so that it didn't interfere with the map background colors too much, but it was also fairly easy to see whether you were inside or outside of the range as you zoomed in.
