### ISSUE TITLE
Bug with lakes and rivers layer?

### ISSUE THREAD

**Issue by hadinon** [ncsco/pinemap-dss-help#96]
When I select a location on the Historical map of the Summer Temperature tool and then check the box to display the lakes and rivers, everything works great: 
![image](https://cloud.githubusercontent.com/assets/886682/13848358/bfdd3154-ec27-11e5-84b6-2e770ab10d0b.png)

However, when I switch to Projected Change or Projected Average, the lakes and rivers layer doesn't display:
![image](https://cloud.githubusercontent.com/assets/886682/13848384/e96ce7ee-ec27-11e5-8d21-c650f74bab7f.png)
![image](https://cloud.githubusercontent.com/assets/886682/13848396/f6e50f1e-ec27-11e5-91d9-3fe6dcb27eaf.png)

Are you able to replicate?

**Comment by daviswx** [comment]
Ah yes.  Turns out I forgot to add the rivers layer to a function that automatically re-adds the other boundary layers when the map is switched.

It should be fixed now.  Let me know if it's not.

**Comment by hadinon** [comment]
Yep, fixed. Thanks!
