### ISSUE TITLE
Time series bugs and suggestions

### ISSUE THREAD

**Issue by daviswx** [ncsco/pinemap-dss-help#98]
At the annual meeting, I noticed a bug with the time series:
- The x-axis labels appear above the time series tooltips, as this example shows:

![image](https://cloud.githubusercontent.com/assets/9257580/15590472/ffc0a06a-2365-11e6-949f-c5f2e94a8312.png)

Also, we have a couple of suggested updates based on discussions at the meeting.  These will help better accommodate the model error visualization.
- Reduce the transparency at the edges of the light gray (RCP 4.5) and dark gray (RCP 8.5) boxes
- Label the historical observed value above the blue bar

At some point, I may also want to sort out the z-index updating so the model error lines and band appear above the data.  I tried this before but the time series tooltips also appeared below these bands, and you couldn't hover over the parts of the bars that were obscured by the error band.

**Comment by daviswx** [comment]
One more bug I noticed with the time series:
- The projected change values are not currently limited to the magnitude of the historical average.  In the case below, the maximum change by end-of-century (28.6 days) is greater than the historical average (27.3 days).

![image](https://cloud.githubusercontent.com/assets/9257580/15680176/9add804e-2722-11e6-9ae7-793c7ce0aae7.png)

**Comment by hadinon** [comment]
Hmmm interesting about the latter. What are your thoughts for how to handle that situation? I forget -- do we account for that on the maps?

**Comment by daviswx** [comment]
After checking all of the tools and my code, we are not filtering any of the Projected Change or Projected Average values on the maps or time series, even if the magnitude is greater than the historical observed value.

![image](https://cloud.githubusercontent.com/assets/9257580/15711322/7bf187a2-27db-11e6-8fa1-c30c2d4dc352.png)

Here's the Projected Average time series for that Oconee County location.  The end-of-century extreme value is given as 1.4 days, but it's actually -1.4 days, as you can see it hanging just below the 0 line.

![image](https://cloud.githubusercontent.com/assets/9257580/15710680/0e26a04c-27d9-11e6-8a09-5f9cbd047a23.png)

Similarly, with the Summer Dryness tool, values are showing up even if they're less than zero:

![image](https://cloud.githubusercontent.com/assets/9257580/15710711/27f6bcfa-27d9-11e6-9504-2a006181f22a.png)

So then question then becomes whether we should limit the map and time series values to realistic bounds.  Certainly it makes sense not to show negative numbers of days or a negative Summer Dryness Index, but I do have two main concerns about limiting this value:

a) It might seem like we're manipulating the data.

b) It may throw off the shading on the time series bars (i.e., the more opaque section corresponding to the mean value may become misaligned) since those bars are drawn based only on the max and min bounds.

But I suppose we should decide on a way to handle this since it would affect multiple tools, including the ecological model output (e.g., the future periods could show negative green weight).

**Comment by daviswx** [comment]
Also, here's one other time series bug I noticed:
- Historical average values in the time series tooltips are showing as a range, and with un-rounded values.  This is true on the Summer Temperature, Summer Precipitation, and Summer Dryness Index tools.

![image](https://cloud.githubusercontent.com/assets/9257580/15711570/9138b0bc-27dc-11e6-8776-d008eb5e35a2.png)

**Comment by daviswx** [comment]
Ryan's recommendation was to check each value after pulling it via an OPeNDAP call and limit it to either 0 or the magnitude of the historical average.  He was not worried about the shading in the time series bars corresponding to the mean value being thrown off by this hard limit.

**Comment by daviswx** [comment]
Task list for items in this issue:
- [X] Fix x-axis labels appearing above the time series tooltips
- [X] Reduce the transparency at the edges of the light gray (RCP 4.5) and dark gray (RCP 8.5) boxes
- [X] Label the historical observed value above the blue bar for the Historical and Projected Average time series
- [x] Limit Projected Change values to the magnitude of the historical average and Projected Average values to numbers greater than 0 for most tools

I am unable to replicate the other bug I noted a few posts up about the historical average values not showing correctly in the tooltips.  I think that bug plus the model error-related browser errors I was getting this morning on the production site might have been because I didn't clear my cache (:tired_face:).  Let me know if you notice those issues, otherwise I'll assume they're not actually problems.

**Comment by daviswx** [comment]
I just did a commit to the public site with some of today's bug fixes, and apparently GitHub decided to close this issue because I tagged it in the commit.  I'm re-opening it since I'm still working on limiting the data to the historical average or zero.

That's taking a little longer than it might if I just put a band-aid on my code since I decided to combine several of the data retrieval files into one.  That should make life a bit easier as we add other tools down the road.

**Comment by daviswx** [comment]
The code for pulling values via OPeNDAP calls for the climate tools has been condensed into one file.  Also, the fix has been implemented for negative Projected Change values greater than the magnitude of the historical observed and Projected Average values less than zero.

I did a few spot checks, including the examples in the screenshots above, and all of them seem to be working correctly now.
